stages:
- stage: Build
  variables:
  - group: Bl0g.Infrastructure.Build
  jobs:
  - job: BuildJob
    pool:
        vmImage: 'ubuntu-latest'
    steps:

    - task: Docker@2
      inputs:
        containerRegistry: 'docker-registry-prd-connection'
        repository: 'bl0g.clusterhealth.webapi'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        buildContext: '$(Build.Repository.LocalPath)/src/Bl0g.ClusterHealth.WebApi'
        tags: |
          $(Build.BuildId)

    - task: PublishPipelineArtifact@1
      inputs:
        artifactName: 'bl0g.clusterhealth.webapi.manifests'
        path: '$(Build.Repository.LocalPath)/tools/deploy/kubernetes'

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  jobs:
  - deployment: Deploy
    displayName: Deploy job
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'blog-deployment'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              artifactName: 'bl0g.clusterhealth.webapi.manifests'
              downloadPath: '$(System.ArtifactsDirectory)/manifests'

          - task: KubernetesManifest@0
            displayName: Create imagePullSecret
            inputs:
              action: createSecret
              secretName: 'AzureDevOpsSecret'
              namespace: 'test'
              dockerRegistryEndpoint: 'docker-registry-prd-connection'
              
          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              namespace: 'test'
              manifests: |
                $(System.ArtifactsDirectory)/manifests/deployment.yml
                $(System.ArtifactsDirectory)/manifests/service.yml
              imagePullSecrets: |
                'AzureDevOpsSecret'
              containers: |
                sigsysblogregistryprd/bl0g.clusterhealth.webapi:$(Build.BuildId)
    

